pipeline {
    agent any

    tools {
        nodejs "Node18"
    }

    parameters {
        choice(
            name: 'TEST_SUITE',
            choices: ['sanity', 'regression'],
            description: 'Select which test suite to run'
        )
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/kashidganesh/Playwright-E2e.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                bat 'npm install'
            }
        }

        stage('Install Browsers') {
            steps {
                bat 'npx playwright install'
            }
        }

        stage('Run Tests with Trace') {
            steps {
                script {
                    echo "Running ${params.TEST_SUITE} test suite..."
                    bat "npx playwright test --grep @${params.TEST_SUITE} --reporter=html --trace on"
                }
            }
        }

        stage('Zip Trace Files') {
            steps {
                bat '''
                if exist playwright-report\\trace (
                    powershell Compress-Archive -Path playwright-report\\trace\\* -DestinationPath playwright-report\\trace.zip -Force
                )
                '''
            }
        }

        stage('Archive Placeholder') {
            steps {
                // Create an empty folder to ensure only the "Build Artifacts" header is visible
                bat 'mkdir artifacts_placeholder'
                archiveArtifacts artifacts: 'artifacts_placeholder/**', allowEmptyArchive: true
            }
        }
    }

    post {
        always {
            echo 'Pipeline completed.'
        }
    }
}
