name: Playwright Tests

on:
  workflow_dispatch:
    inputs:
      suite:
        description: 'Select test suite to run'
        required: true
        default: '@sanity'
        type: choice
        options:
          - '@sanity'
          - '@regression'

jobs:
  test:
    name: Run Playwright Tests
    runs-on: ubuntu-latest

    steps:
      #  Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      #  Install dependencies
      - name: Install dependencies
        run: npm ci

      #  Install Playwright browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      #  Run Playwright tests based on selected suite
      - name: Run Playwright Tests
        run: npx playwright test --grep ${{ github.event.inputs.suite }} --reporter=html

      #  Upload the Playwright HTML Report
      - name: Upload Playwright HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ github.event.inputs.suite }}
          path: playwright-report/
